# Generated by Django 2.2.3 on 2019-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(help_text='创建时间', verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='商品名称', max_length=20, verbose_name='商品名称')),
                ('number', models.IntegerField(default=0, help_text='商品数量', verbose_name='商品数量')),
                ('price', models.FloatField(default=0.0, help_text='商品价格', verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'tb_goods',
                'ordering': ['-update_date', '-pk'],
            },
        ),
    ]
